name: SonarCloud
on:
  push:
    branches:
      - Group-ideas
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ricardopr17-1 -Pcoverage
      - name: cache target
        uses: actions/cache@v3
        with:
          path: |
            target
          key: cache-v1-${{ hashFiles('**/src', '**/pom.xml', '**/.github') }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            target
          key: cache-v1-${{ hashFiles('**/src', '**/pom.xml', '**/.github') }}

      - name: change war name and zip
        run: |
          mv target/iniciativas-0.0.1-SNAPSHOT.war target/app.war
          zip target/package.zip target/app.war

      - name: list
        run: |
          ls -la .
          ls -la target

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cvds-dev2win'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_DEPLOY }}
          package: 'target/package.zip'